---
# straight along the guide

 - name: MongoDB | Fetch signing key
   command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

 - name: MongoDB | Add Mongo repository
   shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
         creates=/etc/apt/sources.list.d/mongodb-org-3.0.list

 - name: install mongodb
   apt: pkg=mongodb-org
        update_cache=yes
        state=present

